# Generated by Django 4.2.2 on 2023-06-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_projectsml_projectno'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsweb',
            name='projectNo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
