# Generated by Django 4.2.2 on 2023-06-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='projectLink',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
